<?php
/**
 * VApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SingularApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace SingularApi\Api;

use \SingularApi\Configuration;
use \SingularApi\ApiClient;
use \SingularApi\ApiException;
use \SingularApi\ObjectSerializer;

/**
 * VApiTest Class Doc Comment
 *
 * @category Class
 * @package  SingularApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for getReport
     *
     * 
     *
     */
    public function test_getReport() {

    }
    
    /**
     * Test case for createProfile
     *
     * 
     *
     */
    public function test_createProfile() {

    }
    
    /**
     * Test case for deleteProfile
     *
     * 
     *
     */
    public function test_deleteProfile() {

    }
    
    /**
     * Test case for queryProfile
     *
     * 
     *
     */
    public function test_queryProfile() {

    }
    
    /**
     * Test case for cancelRecurring
     *
     * 
     *
     */
    public function test_cancelRecurring() {

    }
    
    /**
     * Test case for createRecurring
     *
     * 
     *
     */
    public function test_createRecurring() {

    }
    
    /**
     * Test case for queryRecurring
     *
     * 
     *
     */
    public function test_queryRecurring() {

    }
    
    /**
     * Test case for getStatus
     *
     * 
     *
     */
    public function test_getStatus() {

    }
    
    /**
     * Test case for postTransaction
     *
     * 
     *
     */
    public function test_postTransaction() {

    }
    
    /**
     * Test case for authorize
     *
     * 
     *
     */
    public function test_authorize() {

    }
    
    /**
     * Test case for capture
     *
     * 
     *
     */
    public function test_capture() {

    }
    
    /**
     * Test case for queryTransaction
     *
     * 
     *
     */
    public function test_queryTransaction() {

    }
    
    /**
     * Test case for refund
     *
     * 
     *
     */
    public function test_refund() {

    }
    
    /**
     * Test case for voidTransaction
     *
     * 
     *
     */
    public function test_voidTransaction() {

    }
    
}
