#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGSbpQueryRequest
@end

@interface SWGSbpQueryRequest : SWGObject


@property(nonatomic) NSString* fromdate;

@property(nonatomic) NSString* orderid;

@property(nonatomic) NSString* partnerid;

@property(nonatomic) NSString* partnerkey;

@property(nonatomic) NSString* payeeid;

@property(nonatomic) NSString* profileid;

@property(nonatomic) NSString* todate;

@property(nonatomic) NSString* transactionreference;

@end
