#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGSbpRecurringRequest
@end

@interface SWGSbpRecurringRequest : SWGObject


@property(nonatomic) NSString* address;

@property(nonatomic) NSString* amountoutstanding;

@property(nonatomic) NSString* city;

@property(nonatomic) NSString* country;

@property(nonatomic) NSString* currency;

@property(nonatomic) NSString* cvv;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* expirymmyy;

@property(nonatomic) NSString* frequency;

@property(nonatomic) NSString* nextpaymentdate;

@property(nonatomic) NSString* orderid;

@property(nonatomic) NSString* partnerid;

@property(nonatomic) NSString* partnerkey;

@property(nonatomic) NSString* payeefirstname;

@property(nonatomic) NSString* payeeid;

@property(nonatomic) NSString* payeelastname;

@property(nonatomic) NSString* paymentenddate;

@property(nonatomic) NSString* paymentmode;

@property(nonatomic) NSString* paymentstartdate;

@property(nonatomic) NSString* profileid;

@property(nonatomic) NSString* recurringamount;

@property(nonatomic) NSString* routingnumber;

@property(nonatomic) NSString* state;

@property(nonatomic) NSString* tokenizedaccountnumber;

@property(nonatomic) NSString* udfield1;

@property(nonatomic) NSString* udfield2;

@property(nonatomic) NSString* udfield3;

@property(nonatomic) NSString* zip;

@end
