#import <Foundation/Foundation.h>
#import "SWGSbpQueryRequest.h"
#import "SWGSbpProfile.h"
#import "SWGSbpRecurringRequest.h"
#import "SWGSbpResponse.h"
#import "SWGSbpRequest.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGVApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGVApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGVApi*) sharedAPI;
///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpQueryRequest SbpQueryRequest
/// 
///
/// @return NSArray<SWGSbpQueryRequest>*
-(NSNumber*) getReportWithCompletionBlock :(SWGSbpQueryRequest*) sbpQueryRequest 
    
    completionHandler: (void (^)(NSArray<SWGSbpQueryRequest>* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpProfile SbpProfile
/// 
///
/// @return SWGSbpProfile*
-(NSNumber*) createProfileWithCompletionBlock :(SWGSbpProfile*) sbpProfile 
    
    completionHandler: (void (^)(SWGSbpProfile* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpProfile SbpProfile
/// 
///
/// @return SWGSbpProfile*
-(NSNumber*) deleteProfileWithCompletionBlock :(SWGSbpProfile*) sbpProfile 
    
    completionHandler: (void (^)(SWGSbpProfile* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpQueryRequest SbpQueryRequest
/// 
///
/// @return NSArray<SWGSbpProfile>*
-(NSNumber*) queryProfileWithCompletionBlock :(SWGSbpQueryRequest*) sbpQueryRequest 
    
    completionHandler: (void (^)(NSArray<SWGSbpProfile>* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpRecurringRequest SbpRecurringRequest
/// 
///
/// @return SWGSbpRecurringRequest*
-(NSNumber*) cancelRecurringWithCompletionBlock :(SWGSbpRecurringRequest*) sbpRecurringRequest 
    
    completionHandler: (void (^)(SWGSbpRecurringRequest* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpRecurringRequest SbpRecurringRequest
/// 
///
/// @return SWGSbpResponse*
-(NSNumber*) createRecurringWithCompletionBlock :(SWGSbpRecurringRequest*) sbpRecurringRequest 
    
    completionHandler: (void (^)(SWGSbpResponse* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpQueryRequest SbpQueryRequest
/// 
///
/// @return NSArray<SWGSbpRecurringRequest>*
-(NSNumber*) queryRecurringWithCompletionBlock :(SWGSbpQueryRequest*) sbpQueryRequest 
    
    completionHandler: (void (^)(NSArray<SWGSbpRecurringRequest>* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// 
///
/// @return SWGSbpResponse*
-(NSNumber*) getStatusWithCompletionBlock :
    (void (^)(SWGSbpResponse* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpRequest SbpRequest
/// 
///
/// @return SWGSbpResponse*
-(NSNumber*) postTransactionWithCompletionBlock :(SWGSbpRequest*) sbpRequest 
    
    completionHandler: (void (^)(SWGSbpResponse* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpRequest SbpRequest
/// 
///
/// @return SWGSbpResponse*
-(NSNumber*) authorizeWithCompletionBlock :(SWGSbpRequest*) sbpRequest 
    
    completionHandler: (void (^)(SWGSbpResponse* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpRequest SbpRequest
/// 
///
/// @return SWGSbpResponse*
-(NSNumber*) captureWithCompletionBlock :(SWGSbpRequest*) sbpRequest 
    
    completionHandler: (void (^)(SWGSbpResponse* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpQueryRequest SbpQueryRequest
/// 
///
/// @return NSArray<SWGSbpResponse>*
-(NSNumber*) queryTransactionWithCompletionBlock :(SWGSbpQueryRequest*) sbpQueryRequest 
    
    completionHandler: (void (^)(NSArray<SWGSbpResponse>* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpRequest SbpRequest
/// 
///
/// @return SWGSbpResponse*
-(NSNumber*) refundWithCompletionBlock :(SWGSbpRequest*) sbpRequest 
    
    completionHandler: (void (^)(SWGSbpResponse* output, NSError* error))completionBlock;
    


///
///
/// 
/// Please provide a description for the endpoint
///
/// @param sbpRequest SbpRequest
/// 
///
/// @return SWGSbpResponse*
-(NSNumber*) voidTransactionWithCompletionBlock :(SWGSbpRequest*) sbpRequest 
    
    completionHandler: (void (^)(SWGSbpResponse* output, NSError* error))completionBlock;
    



@end
